version: "3.3"
services:
  replace-server:
    build: .
    container_name: rplace-server
    environment:
      - PUID=1111
      - PGID=1111
      - TZ=Europe/Rome
    networks:
      nginx-net:
        ipv4_address: 10.50.69.210
    ports:
      - 5000:5000
    restart: unless-stopped


networks:
  nginx-net:
    name: nginx-net
    external: true
