version: "3.3"
services:
  replace-server:
    build: .
    container_name: rplace-server
    environment:
      - PUID=1111
      - PGID=1111
      - TZ=Europe/Rome
    #network_mode: host
    networks:
      - nginx-net
    expose:
      - 80
      - 443
    restart: unless-stopped


networks:
  nginx-net:
    name: nginx-net
    external: true
